### ISSUE TITLE
71spiel-sns-motr-repair ST is failing due to m0cat crashes

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1887] opened 2022-06-16 07:20 UTC
```
$ scripts/m0 run-st 71spiel-sns-motr-repair
...
pver is : <0:0>
motr[63328]:  8540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000001:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63328]:  8720  ERROR  [pool/pool_machine.c:531:spare_usage_arr_update]  <7600000000000002:a>: No free spare space slot is found, this pool version is in DUD state; event_index=2 event_state=5
motr[63328]:  8570  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=2 event_state=5
motr[63328]:  8540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63328]:  e8c0  ERROR  [conf/helpers.c:552:m0_conf_process2service_get]  <! rc=-2
motr[63328]:  a9c0  ERROR  [io_req_fop.c:363:io_bottom_half]  ioo=0x301b800 off=1409024 from=10.230.247.7@tcp:12345:33:902 rc=-5 ti_rc=-5 @<4300000800010000:10000>
motr[63328]:  a670  ERROR  [sns/parity_repair.c:72:_spare_next]  <! rc=-2
motr[63328]:  a740  ERROR  [io_pargrp.c:1620:io_spare_map]  <! rc=-2
motr[63328]:  a6a0  FATAL  [lib/assert.c:50:m0_panic]  panic: (rc == 0) at pargrp_iomap_dgmode_process() (motr/io_pargrp.c:1760)  [git: 2.0.0-817-8-g51633a8-dirty] /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63328.2022-06-15-18:04:51
Motr panic: (rc == 0) at pargrp_iomap_dgmode_process() motr/io_pargrp.c:1760 (errno: 0) (last failed: none) [git: 2.0.0-817-8-g51633a8-dirty] pid: 63328  /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63328.2022-06-15-18:04:51
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7f57d3c6ffe0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_panic+0xe6)[0x7f57d3c70196]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x39b164)[0x7f57d3c5e164]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ca6e3)[0x7f57d3c8d6e3]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(ioreq_fop_dgmode_read+0x29e)[0x7f57d3c9859e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d8825)[0x7f57d3c9b825]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d92c0)[0x7f57d3c9c2c0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_sm_asts_run+0xb7)[0x7f57d3d04487]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x36d527)[0x7f57d3c30527]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_thread_trampoline+0x5e)[0x7f57d3c6559e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ade7d)[0x7f57d3c70e7d]
/lib64/libpthread.so.0(+0x7e65)[0x7f57d33ace65]
/lib64/libc.so.6(clone+0x6d)[0x7f57d1d3288d]
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../..//motr/st/utils/sns_repair_common_inc.sh: line 52: 63328 Aborted                 (core dumped) $M0_SRC_DIR/motr/st/utils/m0cat ${MOTR_PARAM} -c ${file_size[$i]} -o ${file[$i]} "$MOTR_M0T1FS_TEST_DIR/${file[$i]}"
pver is : <0:0>
motr[63496]:  1540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000001:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63496]:  1720  ERROR  [pool/pool_machine.c:531:spare_usage_arr_update]  <7600000000000002:a>: No free spare space slot is found, this pool version is in DUD state; event_index=2 event_state=5
motr[63496]:  1570  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=2 event_state=5
motr[63496]:  1540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63496]:  8c10  ERROR  [conf/helpers.c:552:m0_conf_process2service_get]  <! rc=-2
motr[63496]:  99c0  ERROR  [io_req_fop.c:363:io_bottom_half]  ioo=0x3904fe0 off=1769472 from=10.230.247.7@tcp:12345:33:902 rc=-5 ti_rc=-5 @<4300000800010001:10001>
motr[63496]:  9670  ERROR  [sns/parity_repair.c:72:_spare_next]  <! rc=-2
motr[63496]:  9740  ERROR  [io_pargrp.c:1620:io_spare_map]  <! rc=-2
motr[63496]:  96a0  FATAL  [lib/assert.c:50:m0_panic]  panic: (rc == 0) at pargrp_iomap_dgmode_process() (motr/io_pargrp.c:1760)  [git: 2.0.0-817-8-g51633a8-dirty] /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63496.2022-06-15-18:04:55
Motr panic: (rc == 0) at pargrp_iomap_dgmode_process() motr/io_pargrp.c:1760 (errno: 0) (last failed: none) [git: 2.0.0-817-8-g51633a8-dirty] pid: 63496  /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63496.2022-06-15-18:04:55
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7f45b80ddfe0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_panic+0xe6)[0x7f45b80de196]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x39b164)[0x7f45b80cc164]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ca6e3)[0x7f45b80fb6e3]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(ioreq_fop_dgmode_read+0x29e)[0x7f45b810659e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d8825)[0x7f45b8109825]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d92c0)[0x7f45b810a2c0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_sm_asts_run+0xb7)[0x7f45b8172487]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x36d527)[0x7f45b809e527]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_thread_trampoline+0x5e)[0x7f45b80d359e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ade7d)[0x7f45b80dee7d]
/lib64/libpthread.so.0(+0x7e65)[0x7f45b781ae65]
/lib64/libc.so.6(clone+0x6d)[0x7f45b61a088d]
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../..//motr/st/utils/sns_repair_common_inc.sh: line 52: 63496 Aborted                 (core dumped) $M0_SRC_DIR/motr/st/utils/m0cat ${MOTR_PARAM} -c ${file_size[$i]} -o ${file[$i]} "$MOTR_M0T1FS_TEST_DIR/${file[$i]}"
pver is : <0:0>
motr[63678]:  6540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000001:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63678]:  6720  ERROR  [pool/pool_machine.c:531:spare_usage_arr_update]  <7600000000000002:a>: No free spare space slot is found, this pool version is in DUD state; event_index=2 event_state=5
motr[63678]:  6570  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=2 event_state=5
motr[63678]:  6540  ERROR  [pool/pool_machine.c:738:m0_poolmach_state_transit]  <7600000000000002:a>: This pool is in DUD state; event_index=0 event_state=5
motr[63678]:  8320  ERROR  [conf/helpers.c:552:m0_conf_process2service_get]  <! rc=-2
motr[63678]:  89c0  ERROR  [io_req_fop.c:363:io_bottom_half]  ioo=0x354db60 off=884736 from=10.230.247.7@tcp:12345:33:902 rc=-5 ti_rc=-5 @<4300000800010002:10002>
motr[63678]:  8670  ERROR  [sns/parity_repair.c:72:_spare_next]  <! rc=-2
motr[63678]:  8740  ERROR  [io_pargrp.c:1620:io_spare_map]  <! rc=-2
motr[63678]:  86a0  FATAL  [lib/assert.c:50:m0_panic]  panic: (rc == 0) at pargrp_iomap_dgmode_process() (motr/io_pargrp.c:1760)  [git: 2.0.0-817-8-g51633a8-dirty] /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63678.2022-06-15-18:04:59
Motr panic: (rc == 0) at pargrp_iomap_dgmode_process() motr/io_pargrp.c:1760 (errno: 0) (last failed: none) [git: 2.0.0-817-8-g51633a8-dirty] pid: 63678  /var/motr/root/sandbox.st-71spiel-sns-motr-repair/m0trace.63678.2022-06-15-18:04:59
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7f9c6eacdfe0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_arch_panic+0xe6)[0x7f9c6eace196]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x39b164)[0x7f9c6eabc164]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ca6e3)[0x7f9c6eaeb6e3]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(ioreq_fop_dgmode_read+0x29e)[0x7f9c6eaf659e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d8825)[0x7f9c6eaf9825]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3d92c0)[0x7f9c6eafa2c0]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_sm_asts_run+0xb7)[0x7f9c6eb62487]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x36d527)[0x7f9c6ea8e527]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(m0_thread_trampoline+0x5e)[0x7f9c6eac359e]
/root/motr/motr_test_github_workdir/workdir/src/motr/.libs/libmotr.so.2(+0x3ade7d)[0x7f9c6eacee7d]
/lib64/libpthread.so.0(+0x7e65)[0x7f9c6e20ae65]
/lib64/libc.so.6(clone+0x6d)[0x7f9c6cb9088d]
/root/motr/motr_test_github_workdir/workdir/src/motr/st/utils/../../..//motr/st/utils/sns_repair_common_inc.sh: line 52: 63678 Aborted                 (core dumped) $M0_SRC_DIR/motr/st/utils/m0cat ${MOTR_PARAM} -c ${file_size[$i]} -o ${file[$i]} "$MOTR_M0T1FS_TEST_DIR/${file[$i]}"
spiel-sns-repair: FAILURE 1
462.37user 49.43system 12:42.04elapsed 67%CPU (0avgtext+0avgdata 1210188maxresident)k
148832inputs+9693624outputs (315major+6961654minor)pagefaults 0swaps
```

Note: the crashes were there since the time this test was introduced at commit ac0153c1a.

**Comment by cortx-admin** [comment] 2022-06-16 07:23
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32299. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment] 2022-06-16 10:49
> Chandradhar Raval commented in Jira Server:

This issue is duplicate of CORTX-30750. 

Marking this Resolved as Duplicate and the same can be validated once CORTX-30750 is fixed

**Comment by cortx-admin** [comment] 2022-06-16 11:54
> Nagakishore Kommuri commented in Jira Server:

Duplicate

**Comment by andriytk** [comment] 2022-06-16 12:59
Let's keep this issue open here until CORTX-30750 is fixed.

**Closed** 2022-06-16 14:06 UTC
