### ISSUE TITLE
Sustained writes causes Motr to stop responding and require restarting

### ISSUE THREAD

**Issue by allisterb** [Seagate/cortx-motr#1960] opened 2022-07-05 14:48 UTC
### Problem

When using Motr as a backend for IPFS, either, using the S3 data store plugin or the newer [go-ds-motr](https://github.com/allisterb/go-ds-motr) data store plugin, Motr appears to stop responding after attempts to add multiple medium-sized files.  Initially, I thought this behavior happened only with go-ds-motr but it seems to happen also with the S3 data store plugin. When using go-ds-motr attempting to add files to IPFS using the `benchmark.sh` script results in sustained writes to the Motr store and after the script completes these error messages start occurring

```
022-07-05T13:35:18.316Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreihj3mv3iy2s27ept7a26vhkreqvuu2yan33q6zvclm2abq53lhloa) error: op failed: -113 
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac01fd50, item 0x7f1188055020[230] failed with ri_error=-4                                                              
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac03e090, item 0x7f1198084520[230] failed with ri_error=-4                                                              
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac024d70, item 0x7f118807b3f0[230] failed with ri_error=-4                                                              
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac0209b0, item 0x7f11880b4390[230] failed with ri_error=-4                                                              
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac047d70, item 0x7f11882d8a60[230] failed with ri_error=-4                                                              
motr[654319]:  66d0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f11ac035af0, item 0x7f1198129b40[230] failed with ri_error=-4                                                              
motr[654319]:  9c00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  9b90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  9b90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  9c00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
2022-07-05T13:35:18.327Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreic3kpvinteqhxawhe5raj6ossqw4dwujgxkptcxvzv5hnkbc7vz5m) error: op failed: -113 
motr[654319]:  9b90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  9b90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
2022-07-05T13:35:18.328Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreibacjwafblydn5go5zq7cs2rjo5ofhrxadunhdfyrmry3frb6q37i) error: op failed: -113 
motr[654319]:  ec00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  eb90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  eb90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  ec00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  eb90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  eb90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  ec00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  eb90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  eb90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
2022-07-05T13:35:18.331Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreidhc2zvxezhecdorjlc6viycuqato7xkyrebpyocybvakczzw2v4q) error: op failed: -113 
motr[654319]:  ec00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  eb90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  eb90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
2022-07-05T13:35:18.332Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreiabayazvzql4qcylvucy4tyy23ezp4dcthcnwlde64puzzyqtuh7e) error: op failed: -113 
2022-07-05T13:35:18.332Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreiby6zmrn745izbubrvo3yk4lzmicy745a426bua6ybwl33qq6tfme) error: op failed: -113 
2022-07-05T13:35:18.332Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreigmd4eisb3q5a25pswupf7u36gom56ptkirfr6npxdosjv5h4jmjy) error: op failed: -113 
motr[654319]:  cc20   WARN  [ha/entrypoint.c:563:ha_entrypoint_client_fom_tick]  rlk_rc=-110                                                                                                   
^[[3~motr[654319]:  54b0  ERROR  [rpc/frmops.c:576:item_fail]  packet 0x7f1178023190, item 0x7f1188051840[230] failed with ri_error=-4                                                         
motr[654319]:  ec00  ERROR  [cas/client.c:556:cas_req_failure_ast]  <! rc=-4                                                                                                                   
motr[654319]:  eb90  ERROR  [dix/req.c:1481:dix_get_req_resend]  <! rc=-113                                                                                                                    
motr[654319]:  eb90  ERROR  [dix/req.c:1514:dix_get_req_resend]  <! rc=-113                                                                                                                    
2022-07-05T13:35:23.332Z        ERROR   engine  decision/blockstoremanager.go:93        blockstore.GetSize(bafkreihkntzodgbkhdaj5gln6dinjtxbte4ontl7cmi6wx6f6m5ytmsvqu) error: op failed: -113 
motr[654319]:  c9d0   WARN  [ha/link.c:1285:ha_link_outgoing_fop_replied]  rc=-110 nr=2 hl=0x7f11c42e89c0 ep=inet:tcp:161.35.100.177@22001 lq_tags=(confirmed=20 delivered=20 next=20 assign=22
)                                                                                                                                                                                              
motr[654319]:  cc20   WARN  [ha/entrypoint.c:563:ha_entrypoint_client_fom_tick]  rlk_rc=-110                                                                                                   
motr[654319]:  cc20   WARN  [ha/entrypoint.c:563:ha_entrypoint_client_fom_tick]  rlk_rc=-110                                                                                                   
motr[654319]:  cc20   WARN  [ha/entrypoint.c:563:ha_entrypoint_client_fom_tick]  rlk_rc=-110                                                                                                   
```

See this video https://youtu.be/KZgV9AWzEH4 at 1:15. When this happens Motr stops responding completely and requires restarting using `hctl shutdown` and `hctl start`.

### Expected behavior

Motr should continue to operate normally after sustained I/O writes.

### How to reproduce

Run the `benchmark.sh` [script](https://github.com/allisterb/go-ds-motr/blob/master/benchmark.sh) using either the IPFS S3 data store plugin or go-ds-motr plugin or simply run multiple `ipfs add` operations or run the IPFS server for a long period. On a Cloudshare VM using Kubernetes to run CORTX the whole Kubernetes cluster appears to become unresponsive and the host machine appears to lose internet connectivity.

### Deployment information

This happens using Motr installed from :
* CORTX OVA-2.0.0-713 VM on CloudShare
* Packages from 2.0.0-rgw release [here](https://github.com/Seagate/cortx-motr/releases/tag/2.0.0-rgw)

**Comment by cortx-admin** [comment] 2022-07-05 14:49
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33541. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment] 2022-07-12 06:07
Hi @allisterb ,
Can you use latest OVA release 2.0.0-790 and confirm the behavior?

**Comment by chandradharraval** [comment] 2022-07-12 06:08
@nikitadanilov - Can you provide your feedback on scenario mentioned here?

**Comment by chandradharraval** [comment] 2022-07-25 06:26
@allisterb - Did you got chance to test latest OVA release 2.0.0-790 and confirm the behavior?

**Comment by allisterb** [comment] 2022-08-02 12:56
@chandradharraval Hi sorry for the delay in responding. I tried different ways of accessing the Motr service running in the Kubernetes cluster in the OVA but I was not able to connect it from my Motr. Opening the ports on the pods doesn't seem to be sufficient...it seems the actually CDF.yaml config file used to launch Motr needs some changes too. 

Eventually, I just built the 2.0.0.179 version of Motr and Hare directly in the VM and ran it there and I can confirm the behavior I observed continues. The only difference I could see with this version of the is the lack of error messages...now Motr just seems to hang and spin the CPUs after the writing phase without  outputting anything. This might be some peculiarity of the underlying OS config in the VM though.

**Comment by chandradharraval** [comment] 2022-08-09 06:47
Hi @allisterb ,
Any luck in recreating this issue?

**Comment by hessio** [comment] 2022-08-11 11:25
Hi @allisterb are you saying when you create a Motr+HARE cluster on VM client you are not able to use the cluster? What steps did you follow? and what happens when yo complete the setup steps?

**Comment by hessio** [comment] 2022-08-15 14:39
I am waiting to get some info from the user to see if I recreate their issue on my own machine

**Comment by chandradharraval** [comment] 2022-08-17 05:41
Can we also get support bundle logs/m0traces for the reported failure?

**Comment by r-wambui** [comment] 2022-08-24 16:57
@hessio @chandradharraval, @allisterb seems to have replicated the issue on [slack a while ago:](https://cortxcommunity.slack.com/archives/C019S0SGWNQ/p1659455950637969) 
_"Everything works ok till I write a lot of data to Motr. I actually tried diiferent things in the apps like different ways of locking during mutithreaded writes. But even if I linearize everything Motr still appears to stop responding after a lot of data is sent from the app"_

**Comment by novium258** [comment] 2022-08-24 17:17
It sounds like maybe the next step is for us to internally replicate the issue in order to get the logs so we can get back to Allistair with info, instead of waiting for him to provide it to us? @chandradharraval

**Comment by cortx-admin** [comment] 2022-08-25 07:23
> Chandradhar Raval commented in Jira Server:

[~934401] - Can you help reproducing this issue?

**Comment by novium258** [comment] 2022-08-31 16:29
Any updates @chandradharraval ?

**Comment by chandradharraval** [comment] 2022-09-06 06:29
@novium258 , @allisterb ,
I think you are using very old version of motr(11 months). Can you destroy your cluster and setup fresh cluster with latest OVA version(790 or above)?
Note : We have been running CRUD operation test in our internal testing and we do not see such issues.

**Comment by allisterb** [comment] 2022-09-09 23:08
@chandradharraval Sorry I meant I used version 2.0.0-790, not 2.0.0-179. I don't know if what I was seeing could be something peculiar to the Go bindings or maybe something is being done wrong in the IPFS plugin I wrote.

**Comment by hessio** [comment] 2022-09-12 12:47
@chandradharraval is it possible that this issue could be caused by the go bindings?

**Comment by allisterb** [comment] 2022-09-12 13:09
@hessio @chandradharraval This issue: https://github.com/Seagate/cortx-motr/commit/c20bdfbc34e4b030243b3dcffa2fa8ad405195cd relates to the bindings and motr ops hanging due to not handling errors properly. It was fixed but I don't know if a similar issue could still be present in the bindings code.

**Comment by chandradharraval** [comment] 2022-09-13 04:50
@zohebkhann - Can you try setting up cluster as per shared configuration and reproduce this issue?

**Comment by zohebkhann** [comment] 2022-09-13 08:53
@allisterb 
I am seeing below failure:
`[root@smc52-m08 go-ipfs]# go get github.com/allisterb/go-ds-motr/plugin@HEAD
# github.com/allisterb/go-ds-motr/mio
/root/go/pkg/mod/github.com/allisterb/go-ds-motr@v0.0.0-20220704182431-d8486711015d/mio/mio.go:51:24: fatal error: lib/types.h: No such file or directory
 // #include "lib/types.h"
                        ^
compilation terminated.
`

**Comment by shailesh-vaidya** [comment] 2024-02-08 17:12
Closing as an obsolete

**Closed by shailesh-vaidya** 2024-02-08 17:12 UTC
Labels: needs-attention, Triage: DevTeam, Status: L2 Triage
