### ISSUE TITLE
about 54/124 unit tests failed

### ISSUE THREAD

**Issue by yanqingfu** [Seagate/cortx-motr#1505] opened 2022-02-24 06:12 UTC
followed the latest guide https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst, which showed around 54 unit tests failed

storage-dev-ut
spiel-conf-ut
sss-ut
spiel-ci-ut
snscm_net-ut
sns-cm-repair-ut
snscm_storage-ut
snscm_xform-ut
rpc-session-ut
rpc-rcv-session-ut
rpc-machine-ut
rm-ut
poolmach-ut
rpc-packet-encdec-ut
m0d-ut
rpc-link-ut
layout-access-plan-ut
layout-ut
rpc-item-source-ut
rpc-item-ut
isc-service-ut
ha-state-ut
rpc-formation-ut
fdmi-filter-eval-ut
fdmi-fol-ut
fdmi-pd-ut
fis-ut
failure_domains_tree-ut
dix-cm-iter
dix-client-ut
rpc-connection-ut
rconfc-ut
confstr-ut
confc-ut
cm-ut
layout-ut
helpers-ufid-ut
idx-ut
idx-dix
idx-dix-mt
io-ut
io-req-ut
io-req-fop-ut
io-pargrp-ut
io-nw-xfer-ut
ut
cas-service
cas-client
bulk-server-ut
bulk-server-ut
libm0-ut
addb2-base
addb2-consumer
addb2-storage

[failure_log.txt](https://github.com/Seagate/cortx-motr/files/8130083/failure_log.txt)

**Comment by cortx-admin** [comment] 2022-02-24 06:14
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29038. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by yanqingfu** [comment] 2022-02-24 06:18
[root@ssc-vm-g3-rhev4-1122 cortx-motr]# fi_info --version
fi_info: 1.11.2
libfabric: 1.11.2
libfabric api: 1.11

**Comment by cortx-admin** [comment] 2022-02-24 11:34
> Chandradhar Raval commented in Jira Server:

Based on above comments, marking this issue Resolved with resolution "No Work"

**Closed by cortx-admin** 2022-02-24 11:34 UTC

**Comment by yanqingfu** [comment] 2022-02-24 12:48
1. 7d2217c4812719ce8b8dd2216ae39ee6eea7ea7d
2. CentOS 7.9.2009 x86_64
3.  cortx-motr in var
Filesystem                                   Size  Used Avail Use% Mounted on
devtmpfs                                     3.9G     0  3.9G   0% /dev
tmpfs                                        3.9G     0  3.9G   0% /dev/shm
tmpfs                                        3.9G  876K  3.9G   1% /run
tmpfs                                        3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mapper/vg_sysvol-lv_root                 20G  3.1G   16G  17% /
/dev/sda1                                    976M  120M  790M  14% /boot
/dev/mapper/vg_sysvol-lv_tmp                 9.8G   38M  9.2G   1% /tmp
/dev/mapper/vg_sysvol-lv_var                 217G   15G  193G   8% /var
/dev/mapper/vg_sysvol-lv_log                 7.8G   87M  7.3G   2% /var/log
/dev/mapper/vg_sysvol-lv_audit               240M  3.9M  220M   2% /var/log/audit
tmpfs                                        782M     0  782M   0% /run/user/670951
ssc-nfs-home1.colo.seagate.com:/home/670951  2.5T  744G  1.8T  30% /home/670951
4. I didn't see any failure during the setup while following the guide

**Comment by mehjoshi** [comment] 2022-02-28 09:07
This is strange. I ran the complete set of tests once again and did not see any issues.
Can you try to reproduce the issue on a fresh setup? Thanks.

**Comment by chandradharraval** [comment] 2022-03-08 06:44
Hi @yanqingfu ,
Were you able to verify the same?
