### ISSUE TITLE
be-ut panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished()

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1473] opened 2022-02-09 21:18 UTC
```
$ scripts/m0 run-ut -t be-ut:tx_bulk-small_tx
----- run_ut -t be-ut:tx_bulk-small_tx -----
START Iteration: 1 out of 1
be-ut 
  tx_bulk-small_tx  motr[2311147]:  eb00  FATAL  [lib/assert.c:50:m0_panic]  panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished() (be/log_discard.c:182)  [git: 2.0.0-585-33-g46047958] /var/motr/m0ut/m0trace.2311147
Motr panic: (ld_start_tlist_is_empty(&ld->lds_start_q)) at be_log_discard_flush_finished() be/log_discard.c:182 (errno: 0) (last failed: none) [git: 2.0.0-585-33-g46047958] pid: 2311147  /var/motr/m0ut/m0trace.2311147
/home/ant/motr/motr/.libs/libmotr.so.2(m0_arch_backtrace+0x20)[0x7f9c31b090d0]
/home/ant/motr/motr/.libs/libmotr.so.2(m0_arch_panic+0xdf)[0x7f9c31b0927f]
/home/ant/motr/motr/.libs/libmotr.so.2(m0_panic+0x127)[0x7f9c31af7317]
/home/ant/motr/motr/.libs/libmotr.so.2(+0x2d9dbc)[0x7f9c31a46dbc]
/home/ant/motr/motr/.libs/libmotr.so.2(+0x2da8ca)[0x7f9c31a478ca]
/home/ant/motr/motr/.libs/libmotr.so.2(m0_sm_asts_run+0x109)[0x7f9c31b9a299]
/home/ant/motr/motr/.libs/libmotr.so.2(+0x38f2bb)[0x7f9c31afc2bb]
/home/ant/motr/motr/.libs/libmotr.so.2(m0_thread_trampoline+0x5a)[0x7f9c31afe6ca]
/home/ant/motr/motr/.libs/libmotr.so.2(+0x39cdfd)[0x7f9c31b09dfd]
/lib64/libpthread.so.0(+0x814a)[0x7f9c311d314a]
/lib64/libc.so.6(clone+0x43)[0x7f9c2fa5ff23]
```
About 50/50 reproducibility.

Commit 46047958.

**Comment by cortx-admin** [comment] 2022-02-09 21:18
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28678. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nkommuri** [comment] 2022-02-15 10:56
Hi @andriytk , this issue looks similar to https://jts.seagate.com/browse/CORTX-26865. Can you please check once. Thanks.

**Comment by andriytk** [comment] 2022-02-15 11:07
Yes, it looks the same.

**Comment by cortx-admin** [comment] 2022-02-21 07:48
> Chandradhar Raval commented in Jira Server:

Hi [~520414] 

Can we mark this issue Resolved(as resolution Duplicate) as we already have same issue tracked under EOS-26856?

**Comment by cortx-admin** [comment] 2022-02-21 10:39
> Andriy Tkachuk commented in Jira Server:

Why do you think it's the same issue? It doesn't look the same to me. The stack is different, at least.

**Comment by cortx-admin** [comment] 2022-02-21 10:39
> Andriy Tkachuk commented in Jira Server:

Oh, you probably meant CORTX-26865? Then yes - we can close this one. Just make sure to link it with the GitHub issue.

**Comment by nkommuri** [comment] 2022-02-28 06:35
Duplicate of https://jts.seagate.com/browse/CORTX-26865.  Closing this Github issue.

**Comment by cortx-admin** [comment] 2022-02-28 06:37
> Chandradhar Raval commented in Jira Server:

Based on above comments, Marking this Jira Resolved with resolution Duplicate

**Comment by andriytk** [comment] 2022-02-28 13:40
The issue is not fixed yet.

**Closed** 2022-02-28 14:46 UTC
Labels: Triage: DevTeam, Status: L1 Triage

**Comment by cortx-admin** [comment] 2022-02-28 16:58
> Chandradhar Raval commented in Jira Server:

Hi [~520414],

Yes as [~934462] mentioned this will be tracked under CORTX-26865 which is in Open state

**Comment by andriytk** [comment] 2022-03-01 12:25
And which github issue will track it?

**Comment by andriytk** [comment] 2022-04-28 12:14
@chandradharraval, why to close github issue if the issue is not fixed? Is it some strange new policy or something?

**Comment by nezzzu** [comment] 2022-04-28 13:33
@chandradharraval Where is the original/main issue now? The links above do not work for me.

**Comment by nezzzu** [comment] 2022-04-28 15:28
duplicate of #1660
