### ISSUE TITLE
Can/should we create Doxygen?

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#22] opened 2020-08-26 19:01 UTC
Hello @nikitadanilov ,

In https://github.com/Seagate/cortx-motr/pull/233/files/ba835da44d825a329c7c4694087f9e3b7ebea369..dd549c1eec91f9c8bae2d4be430547aea3957c08, I saw that you mentioned Doxygen.  Are the motr source files set up for Doxygen?  If so, are the developers currently using Doxygen auto-generated servers?  If so, where?  If it is not currently set up, or if it is set up but only internal, what do you think about having someone follow this guide and set up public Doxygen for us?

https://gist.github.com/francesco-romano/351a6ae457860c14ee7e907f2b0fc1a5

Thanks,

John

**Comment by huanghua78** [comment] 2020-11-26 02:46
I think we need someone to check the Doxygen building in Motr.

**Comment by nkommuri** [comment] 2021-10-04 16:35
Verified that  Motr Doxygen building  works.
@johnbent , Is this ticket intended for creation of public Doxygen using Github pages? If not, we can close this ticket.

**Comment by johnbent** [comment] 2021-10-04 17:16
@nkommuri yes, this is about creating public doxygen if that would be easy to do and people think it is useful

**Comment by r-wambui** [comment] 2021-11-17 17:42
Hi @johnbent , what are the next steps on this? Does it need to be added to the documentation or the product. If product, has this been planned for future sprints?

**Comment by johnbent** [comment] 2021-11-18 17:45
Hey Rose,

I’m not sure. Perhaps @Trupti ***@***.***> knows?
________________________________

**Comment by truptiatseagate** [comment] 2021-11-23 11:55
@johnbent, @chandradharraval and team will review the request here to setup public Doxygen for Motr repo and they will get back shortly on it.

**Comment by cortx-admin** [comment] 2022-03-28 10:31
> Donald R Bloyer commented in Jira Server:

[~220073] [~517711] [~520423] [~520479] [~536285] [~530903]

I am of the impression that Doxygen is 'there' in our code, but nobody really uses it?  If we really don't use it then we should deprecate it from our 'presumed functional' environment?

**Comment by cortx-admin** [comment] 2022-04-11 06:54
> Chandradhar Raval commented in Jira Server:

We plan to pick this up in PI7

**Comment by cortx-admin** [comment] 2022-04-27 07:28
> Nagakishore Kommuri commented in Jira Server:

Total number of doc files generated after running doxygen...


root@ssc-vm-g2-rhev4-3141 ~/doxygen/cortx-motr/doc (gh-pages) > find . -type f | wc
 *104591* 104604 7124485

**Comment by nkommuri** [comment] 2022-04-28 03:48
Requirement is to host Seagate/cortx-motr documentation via GitHub Pages (a free web service by GitHub for hosting GitHub repositories).
Cortx-motr uses “Doxygen” tool to generate documentation. Idea is, to host  Seagate/cortx-motr repository’s documentation via GitHub Pages and generate documentation automatically upon every commit, which will get reflected in GitHub pages automatically.

To achieve this, we need to commit documentation files, generated by Doxygen, into Seagate/cortx-motr  repository. But the problem is, when we run Doxygen tool on cortx-motr repo, it is producing 100K (new) files, whereas we have only 4K files currently in cortx-motr repo.
We may run into maintenance issues if we commit 100K new files into cortx-motr repository

Alternatives..
•	Create a separate repository, Ex: Seagate/cortx-motr-doc, for storing/maintaining doc files produced by Doxygen tool. We need to update this new repository periodically
•	Instead of hosting Seagate/cortx-motr in GitHub pages, create an rpm file containing Doxygen documentation,  and deliver it with every release.

@johnbent   please provide your suggestion/feedback.

**Comment by johnbent** [comment] 2022-04-28 03:50
I think the github pages approach will be best. Will it still be a problem if the 100K pages go into a doc branch instead of main? I definitely don't like the RPM approach because we want to host it somewhere. The separate repo might be OK but it's disappointing that it doesn't get updated automatically on each commit.

@osowski , thoughts on this?

**Comment by cortx-admin** [comment] 2022-06-20 05:26
> Papan Kumar Singh commented in Jira Server:

create a docs directory in cortx-motr.

moved all files  generated using "make docs" command from cortx-motr/doc/html to 

cortx-motr/docs directory 

Created github page https://papan-singh.github.io/cortx-motr-1/

**Comment by nkommuri** [comment] 2022-08-09 08:11
We tried to host cortx-motr documentation in Github pages by manually committing 100k doc files into Github repo.  Github Page link is provided in above comment [ https://github.com/Seagate/cortx-motr/issues/22#issuecomment-1159988919 ].
But Github pages is not able to load our documentation as we have way too many files [ > 1,00,000 ]. Github pages was able to load some doc pages but failed to load some.

For the time being, any user can run "make doc" to generation documentation and host it on their local machines. Instructions on how to generate the documentation, is provided in cortx-motr quick start guide (https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst)  under "Build the documentation" section.

Closing the ticket.

**Comment by anaghadeshmukh** [comment] 2022-08-09 09:32
Thanks Kishore. 
@johnbent can we close this ticket since doxygen support has been added?

**Comment by anaghadeshmukh** [comment] 2022-08-18 04:26
@johnbent I am closing the issue as per above comment.

**Comment by anaghadeshmukh** [comment] 2022-08-18 04:27
Closing as original purpose of the ticket is completed.

**Closed by anaghadeshmukh** 2022-08-18 04:26 UTC
Labels: needs-attention, Triage: DevTeam, Status: Fix Scheduled, rose

**Comment by cortx-admin** [comment] 2022-08-25 07:23
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding Github issue is closed now.
