### ISSUE TITLE
Problem: hax starts and stops rconfc frequently

### ISSUE THREAD

**Issue by mssawant** [Seagate/cortx-motr#300] opened 2020-12-18 20:54 UTC
Presently fsStatsUpdater in hare starts and stop rconfc frequently to invoke motr spiel command to fetch filesystem statistics which are updated in Consul.

Frequent rconfc start - stop is not very efficient when we need to invoke multiple spiel commands, e.g. to trigger SNS repair/rebalance.
A better way needs to be worked out to deal with this issue.

reference:
https://github.com/Seagate/cortx-motr/issues/298

**Comment by andriytk** [comment] 2020-12-19 12:37
I'd say the problem is not the frequency here, but rather the periodicity: once rconfc is started - it should be running without stopping. The problem with shutting down the cluster (when stopping the hax gets stuck on rconfc stop because there are no confd processes available by the time hax stops) should be handled at Motr side: rconfc must be able to stop even without confd processes running. Meanwhile, as a workaround, we can set a short stop timeout in hax' systemd service configuration file.

**Comment by mssawant** [comment] 2020-12-20 17:50
Idea is to avoid starting and stopping of rconfc and to have rconfc lifetime same as the motr lifetime in hax.
>Meanwhile, as a workaround, we can set a short stop timeout in hax' systemd service configuration file.
Can you suggest a timeout please? I would like to avoid timeout based workarounds. I am trying to move out rconfc start/stop, testing is in-pogress.

**Comment by andriytk** [comment] 2020-12-21 11:09
Currently, on LDR1 the systemd timeout for `hax` to stop is [5 seconds](https://github.com/Seagate/cortx-ha/blob/f267fd788cefad42e54a90c47724fc1ce4897a3a/conf/script/build-ha-io#L574). I think that's fair enough - there is nothing that `hax` should wait for.

**Comment by nkommuri** [comment] 2021-11-02 09:47
@mssawant , Is this issue still relevant?

**Comment by r-wambui** [comment] 2021-11-17 18:03
Hi @andriytk could you please let's know if this has been fixed, or scheduled for a fix or if it's still relevant?

**Comment by nkommuri** [comment] 2021-11-29 06:14
@madhavemuri Can you please provide your feedback/input. Thanks.

**Comment by chandradharraval** [comment] 2022-03-14 06:35
Hi @mssawant ,
Is this still relevant and to be fixed?

**Comment by cortx-admin** [comment] 2022-03-21 07:42
> Chandradhar Raval commented in Jira Server:

Hi [~520478],

Any update on my above question?

**Comment by cortx-admin** [comment] 2022-04-04 14:18
> Mandar Sawant commented in Jira Server:

Hi [~530903], [~534380], this is fixed in latest Hare main and the ticket can be closed now.

**Comment by cortx-admin** [comment] 2022-04-04 15:22
> Vaibhav Prakash Paratwar commented in Jira Server:

As per comments above closing this

**Comment by cortx-admin** [comment] 2022-04-04 15:22
> Vaibhav Prakash Paratwar commented in Jira Server:

,

**Closed by cortx-admin** 2022-04-04 15:22 UTC
Labels: needs-attention, rose, Triage:_DevAd
