### ISSUE TITLE
I/O test failed

### ISSUE THREAD

**Issue by kimika88** [Seagate/cortx-motr#2017] opened 2022-06-30 21:45 UTC
### Problem

motr[15124]:  47c0  ERROR  [io_req.c:1551:device_check]  <! rc=-5 [0x23724c0] too many failures: nodes=0 + svcs=0 + devs=2, allowed: nodes=0 or svcs=0 or devs=0
[a lot of lines like this]

### Expected behavior

no error messsages?

### How to reproduce

Followed this section in the user guide:
https://github.com/kimika88/cortx-hare/blob/patch-1/README.md#hare-we-go

### Deployment information

[root@ssc-vm-g4-rhev4-1317 cortx-motr]# fi_info --version
fi_info: 1.11.2
libfabric: 1.11.2
libfabric api: 1.11
[root@ssc-vm-g4-rhev4-1317 cortx-motr]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

### Additional information

[hare_ssc-vm-g4-rhev4-1317.colo.seagate.com.tar.gz](https://github.com/Seagate/cortx-hare/files/9023590/hare_ssc-vm-g4-rhev4-1317.colo.seagate.com.tar.gz)

**Comment by cortx-admin** [comment] 2022-07-27 11:45
> Vaibhav Prakash Paratwar commented in Jira Server:

Duplicate of CORTX-33119

**Comment by cortx-admin** [comment] 2022-08-09 07:29
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as duplicate of CORTX-33119

**Comment by chandradharraval** [comment] 2022-08-17 05:45
Hi @kimika88 ,
Are you still seeing this issue?

**Closed** 2022-08-17 05:50 UTC
Labels: bug, Status: Fix Scheduled
