### ISSUE TITLE
Test hung or taking more time to pass while "run-st"

### ISSUE THREAD

**Issue by ShrihariWaskar** [Seagate/cortx-motr#20] opened 2020-09-01 17:43 UTC
I did successfully build the motr. I ran unit tests(run-ut) and kernel unit tests(run-kut) which were passed.
then I ran one system test "52motr-singlenode-sanity" which also got passed.
after that when started to run all system tests(run-st), the test was stuck/hung at a point shown in the screenshot.
![motr_system_test_hung](https://user-images.githubusercontent.com/65270162/91887318-438a0100-eca8-11ea-9360-9dfbb692b027.PNG)

I waited for more than 30 minutes but the test could not proceed further. 
I could see the test title "06ham" before hung. 

as per comment from "Hua Huang" on teams chat: 
There might be some bug with this test. You can skip it at this moment. Usually, it takes about ~5 hours to run all the ST tests. 
But some of these test suites have known issues. So they are intentionally skipped. Please refer to ".xperior/testds/motr-single_tests.yaml". If some test cases are marked as "executor : Xperior::Executor::Skip", they are skippped.

System: CentOS 7.7.1908 x86_64 VM
Log attached: [motr_system_test_hung_log.txt](https://github.com/Seagate/cortx-motr/files/5157913/motr_system_test_hung_log.txt)

**Comment by r-wambui** [comment] 2021-11-17 17:58
Hi @madhavemuri and @andriytk has this issue been fixed on the commit ids referenced above?

**Comment by cortx-admin** [comment] 2022-01-05 15:01
> Zoheb Khan commented in Jira Server:

I ran the STs using cmd:  *sudo scripts/m0 run-st.* I ran System tests both ways using lnet and libfab.

No test was hung, though there were some failures as shown in the below screenshot. Not able to reproduce this issue.

*!image-2022-01-05-17-55-32-513.png!*

**Comment by nkommuri** [comment] 2022-01-10 06:19
As per the Zoheb comment, we aren't seeing the issue now which is reported in 2020.  Closing.

**Closed by nkommuri** 2022-01-10 06:19 UTC
Labels: needs-attention, rose, Triage:_DevAd, motr_scrum4

**Comment by cortx-admin** [comment] 2022-01-10 07:21
> Nagakishore Kommuri commented in Jira Server:

Issue is not seen now. Closing.

**Comment by cortx-admin** [comment] 2022-01-10 07:21
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment] 2022-01-10 07:21
> Nagakishore Kommuri commented in Jira Server:

.
